### ISSUE TITLE
list found relations in RelFinder

### ISSUE THREAD

**Issue by bluejoe2008** [grapheco/InteractiveGraph#2]

**Comment by linonetwo** [comment]
We can push a <li /> to a Panel right after https://github.com/bluejoe2008/InteractiveGraph/blob/ef89d80383b017336d204978673b01cbba0c77b0/src/main/javascript/control/RelFinderCtrl.js#L56 using jQuery.

While the best maintainable solution is held edge info in a global state store likes `@rematch/core`, and bind Relation Panel to that store.

**Comment by linonetwo** [comment]
If you don't mind, I would try a PR for this.

**Comment by bluejoe2008** [comment]
ok, thx, your pr is welcome.

**Comment by linonetwo** [comment]
Sorry but I have to ask how to run a development server.
You may have deleted the `package.json` which contains the build script. And there is no `webpack.dev.config` or `.rollup.js` for bundling.

And the source seems to be incomplete because there is no `./src/main/style/xxx.css`. So I can't add new styles. I can't directly add CSS to `interactive-graph.min` since it's the compiled file.

**Comment by bluejoe2008** [comment]
very sorry for that.

actually this is a release project which was built from an external project written in typescript. i will soon provide that one with package.json files in 1-2 days.

**Comment by linonetwo** [comment]
Oh, no wonder why Readme mentioned TS but this project is in ES5. Looking forward to that.

**Comment by bluejoe2008** [comment]
this work is done since version 0.3.1
