### ISSUE TITLE
Add new node and edge

### ISSUE THREAD

**Issue by SmoothJM** [grapheco/InteractiveGraph#36]
I have a question about adding node and edge. I use the app.insertNodes() and app.insertEdges() to add a new node and an edge which between the selected node and the new node, but the label of the new edge and INFO box of the new node did not show. And there is an error like that: 
![image](https://user-images.githubusercontent.com/44306149/93550711-8df4c880-f99e-11ea-9191-3e0e741125f7.png)

**Comment by HC-teemo** [comment]
According to my test, the label of the new edge can be displayed (see figure below). 
![Snipaste_2020-09-18_16-25-02](https://user-images.githubusercontent.com/18690803/93574935-98798700-f9cb-11ea-9c87-84ab40947e01.png)

The Infobox of the new node did not show because the data in the info box comes from the original file (excluding the new node).
IntaractiveGraph does not consider the addition and deletion of data in the design. If you need to add, delete or modify data, it is recommended to store the data on neo4j, and then do the update operation.
Thank you.

**Comment by SmoothJM** [comment]
> According to my test, the label of the new edge can be displayed (see figure below).
> ![Snipaste_2020-09-18_16-25-02](https://user-images.githubusercontent.com/18690803/93574935-98798700-f9cb-11ea-9c87-84ab40947e01.png)
> 
> The Infobox of the new node did not show because the data in the info box comes from the original file (excluding the new node).
> IntaractiveGraph does not consider the addition and deletion of data in the design. If you need to add, delete or modify data, it is recommended to store the data on neo4j, and then do the update operation.
> Thank you.

OK, I change the info box ctrl, that works. Thanks for your replying.
